//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEGATHEQUE.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom :.
        /// </summary>
        public static string DirectorFirstname {
            get {
                return ResourceManager.GetString("DirectorFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom :.
        /// </summary>
        public static string DirectorName {
            get {
                return ResourceManager.GetString("DirectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réalisateur.
        /// </summary>
        public static string DirectorTitle {
            get {
                return ResourceManager.GetString("DirectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réalisateur :.
        /// </summary>
        public static string FilmDirector {
            get {
                return ResourceManager.GetString("FilmDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réalisateur.
        /// </summary>
        public static string FilmDirectorTitle {
            get {
                return ResourceManager.GetString("FilmDirectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note :.
        /// </summary>
        public static string FilmEvaluation {
            get {
                return ResourceManager.GetString("FilmEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string FilmEvaluationTitle {
            get {
                return ResourceManager.GetString("FilmEvaluationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom :.
        /// </summary>
        public static string FilmName {
            get {
                return ResourceManager.GetString("FilmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string FilmNameTilte {
            get {
                return ResourceManager.GetString("FilmNameTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de sortie :.
        /// </summary>
        public static string FilmReleaseDate {
            get {
                return ResourceManager.GetString("FilmReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de sortie.
        /// </summary>
        public static string FilmReleaseDateTitle {
            get {
                return ResourceManager.GetString("FilmReleaseDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILM.
        /// </summary>
        public static string FilmTitle {
            get {
                return ResourceManager.GetString("FilmTitle", resourceCulture);
            }
        }
    }
}
